USE tcc2023;
CREATE TABLE Usuarios (
	Id INT NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(200),
	NumDocumento VARCHAR(50),
	NumTelefone VARCHAR(50),
	Email VARCHAR(200),
	Senha VARCHAR(100),
	PRIMARY KEY (Id)
);